demo_user:
  preparation: True
  bbox_shift: 5
  video_path: "data/video/yongen.mp4"
  audio_clips:
    audio_0: "data/audio/yongen.wav"

user_1:
  preparation: True
  bbox_shift: 5
  video_path: "data/video/yongen.mp4"
  audio_clips:
    audio_0: "data/audio/yongen.wav"

user_2:
  preparation: True
  bbox_shift: 5
  video_path: "data/video/sun.mp4"
  audio_clips:
    audio_0: "data/audio/sun.wav"